#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=30gb,walltime=2:00:00
#PBS -N app-extract-bundles-quickbundles

mkdir -p wmc wmc/tracts

# run AFQ segmentation
if [ ! -f ./wmc/classification.mat ]; then
	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/pyafq:dev ./initialSegmentation.py
fi

if [ -f ./wmc/classification.mat ]; then
	echo "complete"
	exit 0
else
	echo "failed"
	exit 1
fi
